name: BuildTest
on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main

jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: BuildTestUbuntu
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@master
      # Now build in a container with all deps
      - name:  DockerBuildTestPush
        run: docker build --build-arg BUILD_GIT_SHA=$GITHUB_HEAD_REF -t ci-vmesh-ubuntu docker/vmesh-ubuntu/ 